apiVersion: apps/v1
kind: Service
metadata:
  name: house-price-prediction-app-service  # Name of the service
spec:
  selector:
    app: model_deployment_hpp  # Label to match with the pod
  ports:
    - protocol: TCP
      port: 8080  # Port to expose
      targetPort: 5001  # Port to forward to